name: another_flutter_slidable
description: A Flutter implementation of slidable list item with directional slide actions that can be work with TabBar.
version: 1.2.0
homepage: https://thanhdt.dev
github: https://github.com/thanhdang198/flutter_slidable

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  collection:

flutter:
